dist: xenial
language: python
cache: pip
sudo: false
install:
  - pip install tox
script: tox
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: pypy2.7-6.0
      env: TOXENV=pypy
    - python: pypy3.5-6.0
      env: TOXENV=pypy3
    - python: 3.5
      env: TOXENV=flake8

notifications:
  email:
    - IanLee1521@gmail.com
  irc:
    channels:
      - "irc.freenode.org##python-code-quality"
    use_notice: true
    skip_join: true
